// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Authors of the dataset used to generate this file:
//   Copyright (c) 2015-2016 Daniel Oaks <daniel@danieloaks.net>
//   Copyright (c) 2001-2004 Simon Butcher <pickle@alien.net.au>
//   & https://github.com/ircdocs/irc-defs/blob/gh-pages/LICENSE
//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED AND WILL BE OVERWRITTEN.

// Package chanmembers provides constants and variables based on irc
// definitions located here:
//   [Channel Membership Prefixes]
//   - https://defs.ircdocs.horse/defs/chanmembers.html
//   - https://github.com/ircdocs/irc-defs/blob/gh-pages/_data/chanmembers.yaml
//
//   Data revision: v1.60
//
package chanmembers

// ChanPermPrefix is the the prefix character for nicknames to denote status.
type ChanPermPrefix rune

// ChanPermMode is the irc2 mode character associated with this membership.
type ChanPermMode rune

const (
	// Creator -- The user created the channel, but only used for '!'
	// channels according to the RFC.
	//
	//  - obsolete: true
	//  - origin: "RFC2811"
	Creator ChanPermPrefix = '@'
	// CreatorMode -- mode mapping to prefix "Creator".
	CreatorMode ChanPermMode = 'O'
	// Founder -- User created the channel. This user usually cannot be
	// kicked or have this mode taken away by other users. In some software,
	// they may perform actions that operators can, but are at a higher
	// privilege level than either operators or protected users.
	//
	//  - obsolete: false
	//  - origin: "EliteIRCd"
	Founder ChanPermPrefix = '~'
	// FounderMode -- mode mapping to prefix "Founder".
	FounderMode ChanPermMode = 'q'
	// HalfOperator -- User is a channel half-operator, that is they have
	// 'half' the access of a full operator. Half-ops can kick unopped
	// users, voiced users, set channel modes including +v, but not kick ops
	// or deop ops. This leads to greater security on channels.
	//
	//  - obsolete: false
	//  - origin: "Hybrid"
	HalfOperator ChanPermPrefix = '%'
	// HalfOperatorMode -- mode mapping to prefix "HalfOperator".
	HalfOperatorMode ChanPermMode = 'h'
	// Operator -- User is a channel operator. They can kick users, change
	// modes, set other users to operator (or lower) status, etc.
	//
	//  - obsolete: false
	//  - origin: "RFC1459"
	Operator ChanPermPrefix = '@'
	// OperatorMode -- mode mapping to prefix "Operator".
	OperatorMode ChanPermMode = 'o'
	// Protected -- User is "protected". This means they cannot be kicked
	// or have this mode taken away by operators (or other protected users).
	// In some software, they may perform actions that operators can, but at
	// a higher privilege level than operators.
	//
	//  - obsolete: false
	//  - origin: "EliteIRCd"
	Protected ChanPermPrefix = '&'
	// ProtectedMode -- mode mapping to prefix "Protected".
	ProtectedMode ChanPermMode = 'a'
	// Voiced -- Channel member is voiced. They can speak while the channel
	// is being moderated. Some implementations also allow them to speak
	// when barred from access to the channel for some reason (such as being
	// banned)
	//
	//  - obsolete: false
	//  - origin: "RFC1459"
	Voiced ChanPermPrefix = '+'
	// VoicedMode -- mode mapping to prefix "Voiced".
	VoicedMode ChanPermMode = 'v'
)
