// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Authors of the dataset used to generate this file:
//   Copyright (c) 2015-2016 Daniel Oaks <daniel@danieloaks.net>
//   Copyright (c) 2001-2004 Simon Butcher <pickle@alien.net.au>
//   & https://github.com/ircdocs/irc-defs/blob/gh-pages/LICENSE
//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED AND WILL BE OVERWRITTEN.

// Package chantypes provides constants and variables based on irc
// definitions located here:
//   [Channel Type Prefixes]
//   - https://defs.ircdocs.horse/defs/chantypes.html
//   - https://github.com/ircdocs/irc-defs/blob/gh-pages/_data/chantypes.yaml
//
//   Data revision: v1.60
//
package chantypes

// ChanType is the channel type prefix character.
type ChanType rune

const (
	// Local -- This channel type is known only to the server they are
	// created on, and as such only clients on that server can join it. Each
	// instance of this channel type is contained per server.
	//
	//  - origin: "RFC1459"
	Local ChanType = '&'
	// Network -- This channel type is known to all servers that are
	// connected to the network.
	//
	//  - origin: "RFC1459"
	Network ChanType = '#'
	// NetworkSafe -- These channels work similar to the `'#'` channels,
	// except the name is prefixed not only with the `'!'` but also a set of
	// alpha- numeric digits. This is an alternative to the time-stamp
	// method of avoiding channel-takeovers during network splits.
	//
	//  - origin: "RFC2811"
	NetworkSafe ChanType = '!'
	// NetworkUnmoderated -- These unmoderated channels work almost exactly
	// the same as `'#'` channels, except nobody can obtain channel operator
	// status on them. Some implementations seem to set the channel mode to
	// `'+nt'` upon creation, however most implementations act as if modes
	// `+nt` are set but don't announce them as being set.
	//
	//  - origin: "RFC2811"
	NetworkUnmoderated ChanType = '+'
)
